// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWf_JP9AxCKIMjSl-U8zJV6HdcSq3NnO4',
    appId: '1:1015082594251:web:b6714ba4e59800267ad04e',
    messagingSenderId: '1015082594251',
    projectId: 'noteapp-10b65',
    authDomain: 'noteapp-10b65.firebaseapp.com',
    storageBucket: 'noteapp-10b65.appspot.com',
    measurementId: 'G-W4D8H95JJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTo4gWneOQOBcJXtdXQ-gOGQnBd4Oyr-k',
    appId: '1:1015082594251:android:7f744eb56bc56c857ad04e',
    messagingSenderId: '1015082594251',
    projectId: 'noteapp-10b65',
    storageBucket: 'noteapp-10b65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrrUcnKfjfOVllcLD6_tyCdCWXS_0CLg',
    appId: '1:1015082594251:ios:9c6da752669a6ee77ad04e',
    messagingSenderId: '1015082594251',
    projectId: 'noteapp-10b65',
    storageBucket: 'noteapp-10b65.appspot.com',
    iosBundleId: 'com.gdsc.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzrrUcnKfjfOVllcLD6_tyCdCWXS_0CLg',
    appId: '1:1015082594251:ios:2cade22edaf6f3977ad04e',
    messagingSenderId: '1015082594251',
    projectId: 'noteapp-10b65',
    storageBucket: 'noteapp-10b65.appspot.com',
    iosBundleId: 'com.gdsc.myNotes.RunnerTests',
  );
}
